Update README.md
2gis/native-sdk-ios-swift-package pull request #3
Opened 2021-05-13 13:32 UTC by maxal9999

2021-05-13 16:01 UTC, aapng requested changes

2021-05-13 16:01 UTC, aapng commented on README.md
> +Native SDK for working with the map from the 2GIS.
```suggestion
A native iOS SDK for working with the 2GIS map.
```

2021-05-13 16:01 UTC, aapng commented on README.md
> +To install the SDK, it is necessary to add this Swift Package to your project.
```suggestion
In order to use the SDK, add a dependency to this Swift Package to your project.
```

2021-05-13 16:01 UTC, aapng commented on README.md
> +About adding package dependencies you can read [here](https://developer.apple.com/documentation/swift_packages/adding_package_dependencies_to_your_app).
```suggestion
Read [this article](https://developer.apple.com/documentation/swift_packages/adding_package_dependencies_to_your_app) to learn how one can add a package dependency.
```

2021-05-13 17:17 UTC, maxal9999 commented on README.md
> +About adding package dependencies you can read [here](https://developer.apple.com/documentation/swift_packages/adding_package_dependencies_to_your_app).
А в чем тут принципиальная разница?

2021-05-13 17:18 UTC, maxal9999 commented on README.md
> +To install the SDK, it is necessary to add this Swift Package to your project.
А тут не соглашусь. Пункт же называется "Installation" . Соответственно, мы говорим об "how to install", а не "how to use".

2021-05-13 17:21 UTC, aapng commented on README.md
> +About adding package dependencies you can read [here](https://developer.apple.com/documentation/swift_packages/adding_package_dependencies_to_your_app).
Лишнее обращение через you. Также в изначальном предложении неверная структура. Не очень хорошо начинать полное предложение с About.

Использование "learn" уточняет назначение статьи. Иначе не так естественно выглядит текст: нет явности цели чтения "о пакетных зависимостях".

2021-05-13 17:24 UTC, aapng commented on README.md
> +To install the SDK, it is necessary to add this Swift Package to your project.
По-моему, у нас скорее заголовок неверный. Непонятно, что мы хотим высказать под "установкой" и зачем это нужно пользователю.

Есть потребность использовать пакет SDK, вот и всё.

2021-05-13 19:17 UTC, maxal9999 commented on README.md
> +About adding package dependencies you can read [here](https://developer.apple.com/documentation/swift_packages/adding_package_dependencies_to_your_app).
Хз, мне мои варианты также нравились. Поправил.

2021-05-14 09:25 UTC, aapng approved these changes

2021-05-14 11:27 UTC, merged